<a href="https://colab.research.google.com/github/sunrinint/BigData_2021/blob/main/210525_%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EC%9D%B8%EC%BD%94%EB%94%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 데이터 전처리(Data Pre-Processing)
# Garbage in, Garbage out
# 데이터 클린징, 결손값 처리, 데이터 인코딩 (문자열 => 숫자형)
# 데이터 스케일링, 이상치 제거, ...



In [5]:
# 레이블 인코딩(Label Encoding)

from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']



In [8]:
# 객체 생성 => fit() => transform()

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

print(labels)


# 인코딩 값 확인
print(encoder.classes_)

# 디코딩 값 확인
print(encoder.inverse_transform([4,5,2,0,1,1,3]))w

[0 1 4 5 3 3 2 2]
['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [11]:
# 원-핫 인코딩(One-Hot Encoding)
# 문자열 값 => 숫자형 값

from sklearn.preprocessing import OneHotEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

labels = labels.reshape(-1, 1)
print(labels)

[[0]
 [1]
 [4]
 [5]
 [3]
 [3]
 [2]
 [2]]


In [15]:
o_h_encoder = OneHotEncoder()
o_h_encoder.fit(labels)
o_h_labels = o_h_encoder.transform(labels)
o_h_labels.toarray()


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [17]:
# get_dummies() : 문자열 => 숫자형 바꾸는 작업

import pandas as pd

item_df = pd.DataFrame({'item':['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'] })
pd.get_dummies(item_df)


item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0